ALTER TABLE `properties` CHANGE `active` `active` TINYINT(4) NULL DEFAULT '0', CHANGE `featured` `featured` TINYINT(4) NULL DEFAULT '0', CHANGE `name` `name` VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL, CHANGE `contract` `contract` VARCHAR(12) CHARACTER SET utf8 COLLATE utf8_general_ci NULL, CHANGE `type` `type` VARCHAR(11) CHARACTER SET utf8 COLLATE utf8_general_ci NULL, CHANGE `location_id` `location_id` VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL, CHANGE `lat` `lat` VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL, CHANGE `lng` `lng` VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL, CHANGE `image_id` `image_id` TINYINT(4) NULL, CHANGE `user_id` `user_id` INT(11) NULL, CHANGE `price` `price` INT(11) NULL, CHANGE `short_desc` `short_desc` VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL, CHANGE `add_1` `add_1` VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL, CHANGE `add_2` `add_2` VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL, CHANGE `add_3` `add_3` VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL, CHANGE `total_area_int` `total_area_int` INT(4) NULL, CHANGE `total_area_ext` `total_area_ext` INT(4) NULL, CHANGE `no_bath` `no_bath` INT(4) NULL, CHANGE `bedrooms` `bedrooms` INT(4) NULL, CHANGE `lift` `lift` TINYINT(1) NULL DEFAULT '0', CHANGE `security_door` `security_door` TINYINT(1) NULL DEFAULT '1', CHANGE `double_glazing` `double_glazing` TINYINT(1) NULL DEFAULT '1', CHANGE `heating_type` `heating_type` VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL, CHANGE `year_built` `year_built` INT(4) NULL, CHANGE `garage` `garage` TINYINT(1) NULL, CHANGE `garden` `garden` TINYINT(1) NULL, CHANGE `parking` `parking` TINYINT(1) NULL, CHANGE `terrase` `terrase` TINYINT(1) NULL, CHANGE `year_reno` `year_reno` INT(4) NULL, CHANGE `orientation` `orientation` VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL, CHANGE `floor` `floor` INT(2) NULL, CHANGE `garage_no` `garage_no` INT(2) NULL, CHANGE `garage_area` `garage_area` INT(3) NULL, CHANGE `kitchen_type` `kitchen_type` VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL, CHANGE `no_showers` `no_showers` INT(1) NULL, CHANGE `created` `created` DATETIME NULL, CHANGE `modified` `modified` DATETIME NULL, CHANGE `key_feature_1` `key_feature_1` VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL, CHANGE `key_feature_2` `key_feature_2` VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL, CHANGE `key_feature_3` `key_feature_3` VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL;

CREATE TABLE IF NOT EXISTS `property_translations` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `short_desc` text DEFAULT NULL,
  `key_feature_1` text DEFAULT NULL,
  `key_feature_2` text DEFAULT NULL,
  `key_feature_3` text DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

ALTER TABLE `property_translations` ADD `property_id` INT(11) NULL AFTER `id`;
ALTER TABLE `property_translations` ADD `locale` VARCHAR(50) NULL AFTER `property_id`;
ALTER TABLE `property_translations` ADD `name` VARCHAR(500) NULL AFTER `locale`;